export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const ADD_ISSUES_SUCCESS = 'ADD_ISSUES_SUCCESS';
export const DELETE_ISSUES_SUCCESS = 'DELETE_ISSUES_SUCCESS';
export const EDIT_ISSUES_SUCCESS = 'EDIT_ISSUES_SUCCESS';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
